// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dmitry_koscheev_kt_41_23.Database;

#nullable disable

namespace dmitry_koscheev_kt_41_23.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20261006095428_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор записи дисциплины");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_discipline_name")
                        .HasComment("Название дисциплины");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("c_discipline_isDeleted")
                        .HasComment("Удалёна ли дисциплина");

                    b.HasKey("DisciplineId")
                        .HasName("pk_cd_discipline_discipline_id");

                    b.ToTable("cd_discipline", (string)null);
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grade_id")
                        .HasComment("Идентификатор записи оценки");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("int")
                        .HasColumnName("f_discipline_id")
                        .HasComment("Идентификатор дисциплины");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("f_student_id")
                        .HasComment("Идентификатор студента");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("c_grade_value")
                        .HasComment("Значение оценки");

                    b.HasKey("GradeId")
                        .HasName("pk_cd_grade_grade_id");

                    b.HasIndex(new[] { "DisciplineId" }, "idx_cd_grade_fk_f_discipline_id");

                    b.HasIndex(new[] { "StudentId" }, "idx_cd_grade_fk_f_student_id");

                    b.ToTable("cd_grade", (string)null);
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id")
                        .HasComment("Идентификатор записи группы");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<int>("Course")
                        .HasColumnType("int")
                        .HasColumnName("c_group_course")
                        .HasComment("Номер курса");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_group_name")
                        .HasComment("Название группы");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int")
                        .HasColumnName("f_specialty_id")
                        .HasComment("Идентификатор специальности");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("c_group_isDeleted")
                        .HasComment("Удалёна ли группа");

                    b.HasKey("GroupId")
                        .HasName("pk_cd_group_group_id");

                    b.HasIndex(new[] { "SpecialtyId" }, "idx_cd_group_fk_f_specialty_id");

                    b.ToTable("cd_group", (string)null);
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Specialty", b =>
                {
                    b.Property<int>("SpecialtyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("specialty_id")
                        .HasComment("Идентификатор записи Специальности");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecialtyId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_specialty_code")
                        .HasComment("Код специальности");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_specialty_title")
                        .HasComment("Название специальности");

                    b.HasKey("SpecialtyId")
                        .HasName("pk_cd_specialty_specialty_id");

                    b.ToTable("cd_specialty", (string)null);
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id")
                        .HasComment("Идентификатор записи студента");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_student_firstname")
                        .HasComment("Имя студента");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("f_group_id")
                        .HasComment("Идентификатор группы");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(Max)")
                        .HasColumnName("c_student_lastname")
                        .HasComment("Фамилия студента");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("c_student_isDeleted")
                        .HasComment("Удалён ли студент");

                    b.HasKey("StudentId")
                        .HasName("pk_cd_student_student_id");

                    b.HasIndex(new[] { "GroupId" }, "idx_cd_student_fk_f_group_id");

                    b.ToTable("cd_student", (string)null);
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Grade", b =>
                {
                    b.HasOne("dmitry_koscheev_kt_41_23.Models.Discipline", "Discipline")
                        .WithMany("Grades")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_discipline_id");

                    b.HasOne("dmitry_koscheev_kt_41_23.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_student_id");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Group", b =>
                {
                    b.HasOne("dmitry_koscheev_kt_41_23.Models.Specialty", "Specialty")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_specialty_id");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Student", b =>
                {
                    b.HasOne("dmitry_koscheev_kt_41_23.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Discipline", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Specialty", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("dmitry_koscheev_kt_41_23.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
